name: Publish

on:
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          7.0.x
          6.0.x
          3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet restore
    - run: dotnet build --configuration Release laget.Sqids/laget.Sqids.csproj -p:Version=${{vars.VERSION}}.${{github.run_number}}
    - run: dotnet pack --configuration Release laget.Sqids/laget.Sqids.csproj --no-build -p:Version=${{vars.VERSION}}.${{github.run_number}} -p:PackageVersion=${{vars.VERSION}}.${{github.run_number}} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:NuspecFile=laget.Sqids.nuspec
    - run: dotnet nuget push laget.Sqids/bin/Release/laget.Sqids.${{vars.VERSION}}.${{github.run_number}}.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
